server:
  port: 6638

spring:
  application:
    name: u3d-gateway
    
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serverUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true
      
endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true

# hystrix超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

# 动态路由
zuul:
  host:
    maxTotalConnections: 256
    maxPerRouteConnections: 256
  routes:
    u3d-sys-server:
      path: /rest/sys/**
      stripPrefix: false
      serviceId: u3d-sys-server
    