server:
  port: 8888

spring:
  application:
    name: u3d-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: C:/Projects/Config
        encrypt:
          enabled: false

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serverUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true

endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
    