server:
  port: 9001
  contextPath: /rest/sys
    
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serverUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true
  
spring:
  application:
    name: u3d-sys-server
  cloud:
    config:
      failFast: true
      uri: http://127.0.0.1:8888/
      name: database-sys
      profile: default
      
endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true